const images = {
  AppLogo: () => require('../../src/assets/images/app-logo.png'),
  Bot: () => require('../../src/assets/images/bot.png'),
  PhoneIcon: () => require('../../src/assets/images/phone.png'),
  GoogleIcon: () => require('../../src/assets/images/google.png'),
  FacebookIcon: () => require('../../src/assets/images/fb.png'),
  KhmerFlag: () => require('../../src/assets/images/kh-flag.png'),
  VerifyAccount: () => require('../../src/assets/images/verify-account.png'),
  HomeTab: () => require('../../src/assets/images/home-icon.png'),
  TemplateTab: () => require('../../src/assets/images/template-icon.png'),
  BillingTab: () => require('../../src/assets/images/billing-icon.png'),
  AccountTab: () => require('../../src/assets/images/account-icon.png'),
  FillOutIcon: () => require('../../src/assets/images/fill-out.png'),
  CopyIcon: () => require('../../src/assets/images/copy.png'),
  FeatureLogo: () => require('../../src/assets/images/feature-logo.png'),
  ActiveOption: () => require('../../src/assets/images/active-option.png'),
  KHQRICon: () => require('../../src/assets/images/khqr.png'),
  MainCreditIcon: () => require('../../src/assets/images/main-credit.png'),
  CreditIcon: () => require('../../src/assets/images/credit.png'),
  TraingleStar: () => require('../../src/assets/images/traingle-star.png'),
  PaySuccess: () => require('../../src/assets/images/pay-success.png'),
  PersonIcon: () => require('../../src/assets/images/person-icon.png'),
  HistoryIcon: () => require('../../src/assets/images/history-icon.png'),
  HeartIcon: () => require('../../src/assets/images/heart-icon.png'),
  EditIcon: () => require('../../src/assets/images/edit-icon.png'),
  BillingIcon: () => require('../../src/assets/images/billingIcon.png'),
  SecurityIcon: () => require('../../src/assets/images/security-icon.png'),
  TermIcon: () => require('../../src/assets/images/term-icon.png'),
  PrivacyIcon: () => require('../../src/assets/images/privacy-icon.png'),
  LogoutIcon: () => require('../../src/assets/images/logout-icon.png'),
  PremiumIcon: () => require('../../src/assets/images/premium-icon.png'),
  BillingVisaIcon: () => require('../../src/assets/images/billing-visa.png'),
  InvoiceIcon: () => require('../../src/assets/images/invoice.png'),
  DownloadIcon: () => require('../../src/assets/images/download.png'),
  FilterIcon: () => require('../../src/assets/images/filter.png'),
  RewriteIcon: () => require('../../src/assets/images/rewrite-icon.png'),
  ReviewIcon: () => require('../../src/assets/images/review-icon.png'),
  WriteIcon: () => require('../../src/assets/images/write-icon.png'),
  ByeRobotIcon: () => require('../../src/assets/images/bye-robot.png'),
  FBIcon: () => require('../../src/assets/images/fb-icon.png'),
  TelegramIcon: () => require('../../src/assets/images/telegram-icon.png'),
  InstagramIcon: () => require('../../src/assets/images/ig-icon.png'),
  DribbbleIcon: () => require('../../src/assets/images/dribbble-icon.png'),

  // static image
  ItemProfile1: () => require('../../src/assets/static/item-profile1.png'),
  ItemProfile2: () => require('../../src/assets/static/item-profile2.png'),
  ItemProfile3: () => require('../../src/assets/static/item-profile3.png'),
};

export default images;
